services:

  # =========================
  # ODOO (company)
  # =========================
  odoo:
    image: odoo:16
    container_name: odoo
    restart: always
    ports:
      - "8069:8069"
    depends_on:
      - postgres-db
    environment:
      - HOST=postgres-db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./config:/etc/odoo

  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # =========================
  # MYSQL (tu â€“ Spring Boot)
  # =========================
  mysql-server:
    image: mysql:8.0
    container_name: SpringBoot-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CatalegSpring
    volumes:
      - mysql-data:/var/lib/mysql
      - ./SpringBoot/init.sql:/docker-entrypoint-initdb.d/init.sql

  mediaServer-DB:
    image: mysql:8.0
    container_name: mediaServer-db
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediaServer
      MYSQL_USER: mediadmin
      MYSQL_PASSWORD: mediaServer
    volumes:
      - mediaServer:/var/lib/mysql
      - ./mediaServer:/docker-entrypoint-initdb.d

volumes:
  odoo-data:
  postgres-data:
  mysql-data:
  mediaServer:
