services:

  # =========================
  # ODOO (company)
  # =========================
  odoo: 
    build:
      context: .
      dockerfile: Odoo/Dockerfile
    restart: always
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ../Odoo/extra-addons:/mnt/extra-addons
      - ../Odoo/config:/etc/odoo
  
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # =========================
  # MYSQL (tu â€“ Spring Boot)
  # =========================
  mysql-server:
    image: mysql:8.0
    container_name: SpringBoot-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CatalegSpring
    volumes:
      - mysql-data:/var/lib/mysql
      - ./SpringBoot/init.sql:/docker-entrypoint-initdb.d/init.sql

  mediaServer-DB:
    image: mysql:8.0
    container_name: mediaServer-db
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediaServer
      MYSQL_USER: mediadmin
      MYSQL_PASSWORD: mediaServer
    volumes:
      - mediaServer:/var/lib/mysql
      - ./mediaServer:/docker-entrypoint-initdb.d

volumes:
  odoo-data:
  db-data:
  mysql-data:
  mediaServer:
