services:

  # =========================
  # ODOO (company)
  # =========================
  odoo: 
    build:
      context: .
      dockerfile: Odoo/Dockerfile
    container_name: Odoo
    restart: unless-stopped
    ports:
      - "8069:8069"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      ODOO_MASTER_PASSWORD: ${ODOO_MASTER_PASSWORD}
      HOST: db
      USER: ${MYSQL_USER}
      PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - odoo-data:/var/lib/odoo
      - ../Odoo/extra-addons:/mnt/extra-addons
      - ../Odoo/config:/etc/odoo
      - ./Odoo/modulos-zip:/mnt/modulos-zip:ro
  
  db:
    image: postgres:14
    container_name: Postgres
    restart: unless-stopped
    env_file:
    - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # =========================
  # MYSQL (tu â€“ Spring Boot)
  # =========================
  mysql-server:
    image: mysql:8.0
    container_name: SpringBoot-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
      - "33060:33060"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./SpringBoot/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  odoo-data:
  db-data:
  mysql-data:
